apiVersion: v1
data:
    .production.env: |-
        JWT_SECRET=$JWT_SECRET
        MYSQL_DB_HOST=$MYSQL_DB_HOST
        MYSQL_DB_PORT=$MYSQL_DB_PORT
        MYSQL_DB_NAME=$MYSQL_DB_NAME
        MYSQL_DB_USERNAME=$MYSQL_DB_USERNAME
        MYSQL_DB_PASSWORD=$MYSQL_DB_PASSWORD
kind: Secret
metadata:
    name: main-service-secrets
---
apiVersion: v1
data:
    node-environment: production
    pm2-public-key: $PM2_PUBLIC_KEY
    pm2-secret-key: $PM2_SECRET_KEY
kind: Secret
metadata:
    name: main-service-internal
